# Generated by Django 2.2.5 on 2019-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190913_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rounding_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Truncate'), (2, '4/5'), (3, '5/6')], default=4),
        ),
    ]
