# Generated by Django 2.2.5 on 2019-09-16 00:33

import django.core.validators
from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190913_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='point',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-200000), django.core.validators.MaxValueValidator(200000), event.models.IntegerUnitValidator(100)]),
        ),
    ]
