# Generated by Django 2.2.5 on 2019-09-16 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190916_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.PositiveSmallIntegerField(choices=[(3, '三人麻雀'), (4, '四人麻雀')], default=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='point_at_start',
            field=models.PositiveSmallIntegerField(default=25000, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(30000)], verbose_name='配給原点'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rounding_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Truncate'), (2, '4/5'), (3, '5/6')], default=4, verbose_name='端数処理'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='入力任意', max_length=50, null=True, verbose_name='イベント名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uma_method',
            field=models.CharField(choices=[('A1', '5-10'), ('A2', '10-20'), ('A3', '10-30'), ('B1', 'マルA式'), ('B2', 'B2'), ('B3', 'B3')], default='B1', max_length=2, verbose_name='ウマ計算方法'),
        ),
    ]
