# Generated by Django 2.2.5 on 2019-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190916_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='※入力任意', max_length=50, null=True, verbose_name='イベント名'),
        ),
    ]
